export const ATTR_POSITION = 'a'
export const ATTR_NORMAL = 'b'
export const ATTR_UV = 'c'

export const U_MODELMATRIX = 'd'
export const U_VIEWMATRIX = 'e'
export const U_PROJECTIONMATRIX = 'g'
export const U_NORMALMATRIX = 'h'
export const U_COLOR = 'j'
export const U_TIME = 'k'
export const U_TEXTURE = 'm'
export const U_TEXTURE_STARS = 'm2'
export const U_GALAXY_CENTER = 'n'
export const U_TILE_CENTER = 'o'
export const U_TILE_CONNECTION = 'p'
export const U_WORLD_SIZE = 'ws'
export const U_TILE_POS = 'tp'