export const classNames = {
  header: 'a',
  progress: 'b',
  button: 'c',
  wrapper: 'd',
  intro: 'e',
  dismiss: 'f',
  menu: 'g',
  undo: 'h',
  openMenu: 'i',
  new: 'j',
  ui: 'k',
  _hidden: 'l',
  modal: 'm',
  loading: 'n',
  restart: 'o',
  solve: 'p',
  topButtons: 'q',
  bottomButtons: 'r',
  congratulations: 's'
}